networks:
  landregistry:
    name: landregistry_network

volumes:
  orderer.orderer.landregistry.gov:
  peer0.registry.landregistry.gov:
  peer1.registry.landregistry.gov:
  peer0.revenue.landregistry.gov:
  peer0.bank.landregistry.gov:

services:

  ca.registry.landregistry.gov:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-registry
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/registry:/etc/hyperledger/fabric-ca-server
    container_name: ca.registry.landregistry.gov
    networks:
      - landregistry

  ca.revenue.landregistry.gov:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-revenue
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/revenue:/etc/hyperledger/fabric-ca-server
    container_name: ca.revenue.landregistry.gov
    networks:
      - landregistry

  ca.bank.landregistry.gov:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/bank:/etc/hyperledger/fabric-ca-server
    container_name: ca.bank.landregistry.gov
    networks:
      - landregistry

  orderer.orderer.landregistry.gov:
    container_name: orderer.orderer.landregistry.gov
    image: hyperledger/fabric-orderer:2.5.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:17050
    working_dir: /root
    command: orderer
    volumes:
      - ./organizations/ordererOrganizations/orderer.landregistry.gov/orderers/orderer.orderer.landregistry.gov/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/orderer.landregistry.gov/orderers/orderer.orderer.landregistry.gov/tls:/var/hyperledger/orderer/tls
      - orderer.orderer.landregistry.gov:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 17050:17050
    networks:
      - landregistry

  peer0.registry.landregistry.gov:
    container_name: peer0.registry.landregistry.gov
    image: hyperledger/fabric-peer:2.5.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=landregistry_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.registry.landregistry.gov
      - CORE_PEER_ADDRESS=peer0.registry.landregistry.gov:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.registry.landregistry.gov:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.registry.landregistry.gov:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.registry.landregistry.gov:7051
      - CORE_PEER_LOCALMSPID=RegistryDeptMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
    volumes:
      - ./organizations/peerOrganizations/registry.landregistry.gov/peers/peer0.registry.landregistry.gov/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/registry.landregistry.gov/peers/peer0.registry.landregistry.gov/tls:/etc/hyperledger/fabric/tls
      - peer0.registry.landregistry.gov:/var/hyperledger/production
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 17051:17051
    networks:
      - landregistry

  peer1.registry.landregistry.gov:
    container_name: peer1.registry.landregistry.gov
    image: hyperledger/fabric-peer:2.5.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=landregistry_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.registry.landregistry.gov
      - CORE_PEER_ADDRESS=peer1.registry.landregistry.gov:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.registry.landregistry.gov:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.registry.landregistry.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.registry.landregistry.gov:8051
      - CORE_PEER_LOCALMSPID=RegistryDeptMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17052
    volumes:
      - ./organizations/peerOrganizations/registry.landregistry.gov/peers/peer1.registry.landregistry.gov/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/registry.landregistry.gov/peers/peer1.registry.landregistry.gov/tls:/etc/hyperledger/fabric/tls
      - peer1.registry.landregistry.gov:/var/hyperledger/production
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 8051:8051
      - 17052:17052
    networks:
      - landregistry

  peer0.revenue.landregistry.gov:
    container_name: peer0.revenue.landregistry.gov
    image: hyperledger/fabric-peer:2.5.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=landregistry_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.revenue.landregistry.gov
      - CORE_PEER_ADDRESS=peer0.revenue.landregistry.gov:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.revenue.landregistry.gov:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.revenue.landregistry.gov:9051
      - CORE_PEER_LOCALMSPID=RevenueDeptMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17053
    volumes:
      - ./organizations/peerOrganizations/revenue.landregistry.gov/peers/peer0.revenue.landregistry.gov/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/revenue.landregistry.gov/peers/peer0.revenue.landregistry.gov/tls:/etc/hyperledger/fabric/tls
      - peer0.revenue.landregistry.gov:/var/hyperledger/production
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 17053:17053
    networks:
      - landregistry

  peer0.bank.landregistry.gov:
    container_name: peer0.bank.landregistry.gov
    image: hyperledger/fabric-peer:2.5.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=landregistry_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.bank.landregistry.gov
      - CORE_PEER_ADDRESS=peer0.bank.landregistry.gov:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.landregistry.gov:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.landregistry.gov:11051
      - CORE_PEER_LOCALMSPID=BankOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    volumes:
      - ./organizations/peerOrganizations/bank.landregistry.gov/peers/peer0.bank.landregistry.gov/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/bank.landregistry.gov/peers/peer0.bank.landregistry.gov/tls:/etc/hyperledger/fabric/tls
      - peer0.bank.landregistry.gov:/var/hyperledger/production
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 11051:11051
      - 17054:17054
    networks:
      - landregistry

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.9
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.registry.landregistry.gov:7051
      - CORE_PEER_LOCALMSPID=RegistryDeptMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/registry.landregistry.gov/peers/peer0.registry.landregistry.gov/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/registry.landregistry.gov/peers/peer0.registry.landregistry.gov/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/registry.landregistry.gov/peers/peer0.registry.landregistry.gov/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/registry.landregistry.gov/users/Admin@registry.landregistry.gov/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - landregistry